Kevin
pipelin10/example-class pull request #12
Opened 2023-03-29 02:44 UTC by QuewarG

2023-03-29 02:46 UTC, pipelin10 reviewed
Quita los espacios extra

2023-03-29 03:24 UTC, pipelin10 requested changes
Remove the extra spaces

2023-03-30 00:37 UTC, QuewarG commented
Se quita los espacios en blanco

2023-03-30 00:43 UTC, pipelin10 requested changes
Update your branch with main branch in my repo.

```bash
git pull upstream main
```

2023-03-30 00:56 UTC, closed without merging